language: clojure
script: 
  - lein test
  - lein clean
  - lein garden once
  - lein cljsbuild once min
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: resources/public
  on:
    branch: master